name: Build Kamino

on:
  push:
    branches:
      - '**'

jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install
      - name: Jest Test
        run: yarn test
